sudo: required
language: node_js
services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1
  TRAVIS_NODE_VERSION: 11.3.0

before_install:
 - rm -rf ~/.nvm && mkdir ~/.nvm
 - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - export PATH=./node_modules/.bin:$PATH
 - docker-compose --version
 - export TAG=$(git log -1 --pretty=%h)
jobs:
  include:
    - stage: create docker image
      script:
       - docker pull datanchorio/headless-vnc-ubuntu:latest
       - docker build . -t datanchorio/headless-vnc-ubuntu:$TAG --cache-from datanchorio/headless-vnc-ubuntu:latest
       - docker tag datanchorio/headless-vnc-ubuntu:$TAG datanchorio/headless-vnc-ubuntu:latest
       - docker push datanchorio/headless-vnc-ubuntu
notifications:
    slack: datanchorio:6WRWUkwYc1NfxXvlFzHS1f33